baseurl = "/"
title = "Microservices Lab"

enableGitInfo = true

languageCode = "en-us"

contentDir = "content/en"

[minify]
disableSVG = true

# default content language
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false


disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"


[Languages]
[Languages.en]
title = "Microservices Lab"
languageName = "English"
weight = 1


# navigation
[Languages.en.menu]

[[Languages.en.menu.main]]
weight = 3
name = "acend gmbh"
url = "https://www.acend.ch"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    LineNos = true
  # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
  style = "monokai"
  # Uncomment if you want your chosen highlight style used for code blocks without a specified language
  guessSyntax = "true"

[params]

copyright = "Puzzle ITC GmbH"
github_repo = "https://github.com/acend/microservices-lab"
github_branch = "main"

enabledModule = "base"

# Enable Lunr.js offline search
offlineSearch = true

# define base url and path for used code
lab_git_repo = "https://github.com/acend/microservices-lab"
lab_rawgit_repo = "https://raw.githubusercontent.com/acend/microservices-lab/main"
lab_code_basedir = "/code/"

solution_git_repo = "https://github.com/acend/microservices-lab"
solution_rawgit_repo = "https://raw.githubusercontent.com/acend/microservices-lab/main"
solution_code_basedir = "/solution/"

# specify folder structure
folder_monolith = "monolith"
folder_rest = "rest"
folder_kafka = "kafka"
folder_debezium = "debezium"

# Container repos and naming
puzzle_docker_repo = "quay.io/puzzle"
image_prefix = "microservices-lab-"
debezium_docker_repo = "quay.io/debezium"

# Lab Duration
labDuration = "four-hours"
four-hours-text = "Since the time for the labs is limited this step has already been implemented in your version. For a better understanding we encourage you to have a quick read but you may also skip it."

[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = true

############################## social links ##############################
[params.links]
[[params.links.developer]]
name = "GitHub"
icon = "fab fa-github" 
url = "https://github.com/acend/microservices-lab"

[[params.links.user]]
name = "Twitter"
icon = "fab fa-twitter"
url = "https://twitter.com/acend"
  
[[params.links.user]]
name = "LinkedIn"
icon = "fab fa-linkedin-in"
url = "https://www.linkedin.com/company/acend/"


[module]
  [module.hugoVersion]
    extended = true
    min = "0.100.0"
  [[module.imports]]
    path = "github.com/acend/docsy-acend"
    disable = false
  [[module.imports]]
    path = "github.com/acend/docsy-plus"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false
